import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar structure matching Brainboard docs (SUMMARY.md).
 * - type: 'html' → non-clickable uppercase section headers
 * - Doc items: icon className auto-derived from frontmatter `icon` field
 *   via parseFrontMatter in docusaurus.config.ts
 * - Category items: className set from their README's icon field
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // ── Top-level welcome ──────────────────────────────────────────────────
    "index",

    // ── GETTING STARTED ────────────────────────────────────────────────────
    { type: "html", value: "Getting Started", className: "sidebar-section-header" },
    "getting-started/fast-track",
    "getting-started/start-with-template",
    "getting-started/start-with-ai",
    "getting-started/use-cases-videos",
    {
      type: "category",
      label: "Brainboard philosophy",
      className: "sidebar-item-icon icon-sparkles",
      items: [
        "getting-started/brainboard-philosophy/design-first",
        "getting-started/brainboard-philosophy/one-end-to-end-platform",
      ],
    },

    // ── CLOUD DESIGN ───────────────────────────────────────────────────────
    { type: "html", value: "Cloud Design", className: "sidebar-section-header" },
    {
      type: "category",
      label: "Left Pane",
      className: "sidebar-item-icon icon-shapes",
      items: [
        "cloud-design/left-bar/cloud-resources",
        {
          type: "category",
          label: "Input & output",
          items: [
            "cloud-design/left-bar/input-and-output/variables",
            "cloud-design/left-bar/input-and-output/locals",
            "cloud-design/left-bar/input-and-output/output",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Design area",
      className: "sidebar-item-icon icon-diagram-project",
      items: [
        "cloud-design/design-area/node",
        "cloud-design/design-area/connectors",
        "cloud-design/design-area/inheritance",
        "cloud-design/design-area/connection-between-resources",
        "cloud-design/design-area/versioning",
        "cloud-design/design-area/documentation",
        "cloud-design/design-area/collaboration-multi-user",
        "cloud-design/design-area/graphics",
        "cloud-design/design-area/multi-cloud",
        "cloud-design/design-area/provider-specific-configurations",
      ],
    },
    "cloud-design/right-panel",
    "cloud-design/one-action",
    "cloud-design/code-edition",
    {
      type: "category",
      label: "Autogenerated code",
      className: "sidebar-item-icon icon-wand-sparkles",
      items: [
        "cloud-design/autogenerated-code/what-and-how-code-is-generated",
        "cloud-design/autogenerated-code/split-code-into-files",
        "cloud-design/autogenerated-code/terraform-opentofu-actions",
        "cloud-design/autogenerated-code/download-code",
        "cloud-design/autogenerated-code/pull-requests",
      ],
    },

    // ── DATA ───────────────────────────────────────────────────────────────
    { type: "html", value: "Data", className: "sidebar-section-header" },
    {
      type: "category",
      label: "Data structure",
      className: "sidebar-item-icon icon-folder-tree",
      items: [
        "data/data-structure/projects",
        "data/data-structure/environments",
        {
          type: "category",
          label: "Cloud architecture",
          items: [
            "data/data-structure/cloud-architecture/terraform-files",
            "data/data-structure/cloud-architecture/readme-file",
            "data/data-structure/cloud-architecture/synced-architectures",
            "data/data-structure/cloud-architecture/remote-backend",
          ],
        },
        "data/data-structure/template",
      ],
    },
    {
      type: "category",
      label: "Cloud providers",
      key: "data-cloud-providers",
      className: "sidebar-item-icon icon-shapes",
      items: [
        "data/cloud-providers/supported-cloud-providers",
        "data/cloud-providers/customize-provider-configuration",
        "data/cloud-providers/unsupported-cloud-providers",
      ],
    },
    {
      type: "category",
      label: "Terraform / OpenTofu",
      className: "sidebar-item-icon icon-rectangle-code",
      items: [
        {
          type: "category",
          label: "Modules",
          items: [
            "data/terraform-opentofu/terraform-modules/module",
            "data/terraform-opentofu/terraform-modules/import-modules",
            "data/terraform-opentofu/terraform-modules/manage-modules",
            "data/terraform-opentofu/terraform-modules/terraform-registry-credentials",
            "data/terraform-opentofu/terraform-modules/use-modules",
          ],
        },
      ],
    },
    "data/disaster-recovery",

    // ── AUTOMATION ─────────────────────────────────────────────────────────
    { type: "html", value: "Automation", className: "sidebar-section-header" },
    "automation/ci-cd-designer",
    {
      type: "category",
      label: "Supported plugins",
      className: "sidebar-item-icon icon-puzzle",
      items: [
        "automation/supported-plugins/terraform",
        {
          type: "category",
          label: "Security",
          items: [
            "automation/supported-plugins/security/trivy",
            "automation/supported-plugins/security/tfsec",
            "automation/supported-plugins/security/terrascan",
            "automation/supported-plugins/security/opa",
            "automation/supported-plugins/security/checkov",
          ],
        },
        {
          type: "category",
          label: "Cost estimation",
          items: ["automation/supported-plugins/cost-estimation/infracost"],
        },
        {
          type: "category",
          label: "Notifications",
          items: [
            "automation/supported-plugins/notifications/email",
            "automation/supported-plugins/notifications/slack",
            "automation/supported-plugins/notifications/microsoft-teams",
          ],
        },
        "automation/supported-plugins/webhooks",
      ],
    },
    "automation/pipelines",
    "automation/workflow-templates",
    {
      type: "category",
      label: "Drift detection",
      className: "sidebar-item-icon icon-sensor-cloud",
      items: [
        "automation/drift/types-of-drift",
        "automation/drift/remediation",
      ],
    },
    {
      type: "category",
      label: "Self-Hosted Runner",
      className: "sidebar-item-icon icon-house-lock",
      items: [
        "automation/self-hosted-runner/runner-docker-compose",
        "automation/self-hosted-runner/runner-kubernetes",
      ],
    },
    "automation/api",

    // ── SETTINGS ───────────────────────────────────────────────────────────
    { type: "html", value: "Settings", className: "sidebar-section-header" },
    "settings/overview",
    {
      type: "category",
      label: "Authentication",
      className: "sidebar-item-icon icon-right-to-bracket",
      items: [
        "settings/authentication/login",
        "settings/authentication/sso",
      ],
    },
    "settings/account",
    "settings/organization",
    "settings/invite-members",
    "settings/teams",
    {
      type: "category",
      label: "Roles & Permissions (RBAC)",
      className: "sidebar-item-icon icon-user-lock",
      items: [
        "settings/rbac/levels",
        "settings/rbac/roles",
        "settings/rbac/update",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      className: "sidebar-item-icon icon-key-skeleton-left-right",
      items: [
        {
          type: "category",
          label: "Git configuration",
          className: "sidebar-item-icon icon-code-pull-request",
          items: [
            "settings/integrations/git-configuration/github",
            "settings/integrations/git-configuration/ado",
            "settings/integrations/git-configuration/bitbucket",
            "settings/integrations/git-configuration/gitlab",
            "settings/integrations/git-configuration/pull-requests",
          ],
        },
        {
          type: "category",
          label: "Cloud providers",
          key: "settings-cloud-providers",
          className: "sidebar-item-icon icon-cloud-check",
          items: [
            "settings/integrations/cloud-providers/aws",
            "settings/integrations/cloud-providers/azure",
            "settings/integrations/cloud-providers/gcp",
            "settings/integrations/cloud-providers/oci",
          ],
        },
      ],
    },

    // ── SECURITY ───────────────────────────────────────────────────────────
    { type: "html", value: "Security", className: "sidebar-section-header" },
    "security/data",
    "security/soc2",
    "security/rbac",

    // ── HELP & FAQ ─────────────────────────────────────────────────────────
    { type: "html", value: "Help & FAQ", className: "sidebar-section-header" },
    "help-and-faq/shortcuts",
    "help-and-faq/faq",
    {
      type: "category",
      label: "Enterprise customers",
      className: "sidebar-item-icon icon-building",
      items: [
        {
          type: "category",
          label: "Migration",
          className: "sidebar-item-icon icon-right-left",
          items: [
            "help-and-faq/enterprise-customers/migration/import-from-azure",
            "help-and-faq/enterprise-customers/migration/aws-import",
          ],
        },
        "help-and-faq/enterprise-customers/support-vs-professional-services",
      ],
    },
    "help-and-faq/support",
    "help-and-faq/glossary",

    // ── CHANGELOG ──────────────────────────────────────────────────────────
    { type: "html", value: "Changelog", className: "sidebar-section-header" },
    "changelog/2025",
  ],
};

export default sidebars;
