import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  tutorialSidebar: [
    {
      type: 'doc',
      key: '_', id: 'README',
      label: '首页',
    },
    {
      type: 'category',
      label: '开发指南',
      items: [
        { type: 'doc', key: 'getting_started', id: 'guides/getting-started', label: '新人入门指南' },
        { type: 'doc', key: 'concepts_', id: 'guides/concepts', label: '核心概念讲解' },
        { type: 'doc', key: 'setup_', id: 'guides/setup', label: '环境搭建指南' },
        { type: 'doc', key: 'new_feature', id: 'guides/new-feature', label: '新功能开发指南' },
        { type: 'doc', key: 'debugging_', id: 'guides/debugging', label: '调试与排错指南' },
        { type: 'doc', key: 'log_troubleshooting', id: 'guides/log-troubleshooting-guide', label: '日志排查手册' },
        { type: 'doc', key: 'build_deploy', id: 'guides/build-deploy', label: '构建发布指南' },
      ],
    },
    {
      type: 'category',
      label: '架构设计',
      items: [
        { type: 'doc', key: 'overview_', id: 'architecture/overview', label: '项目整体架构' },
        { type: 'doc', key: 'main_process', id: 'architecture/main-process', label: '主进程架构' },
        { type: 'doc', key: 'renderer_process', id: 'architecture/renderer-process', label: '渲染进程架构' },
        { type: 'doc', key: 'ipc_communication', id: 'architecture/ipc-communication', label: 'IPC 通信机制' },
        { type: 'doc', key: 'data_flow', id: 'architecture/data-flow', label: '数据流架构' },
        { type: 'doc', key: 'file_statistics', id: 'architecture/file-statistics', label: '项目文件统计' },
        { type: 'doc', key: 'multi_space', id: 'architecture/multi-space-architecture', label: '多空间架构' },
        { type: 'doc', key: 'security_architecture', id: 'architecture/security-architecture', label: '安全架构' },
      ],
    },
    {
      type: 'category',
      label: '核心模块',
      items: [
        { type: 'doc', key: 'window_management', id: 'modules/window-management', label: '窗口管理' },
        { type: 'doc', key: 'data_storage', id: 'modules/data-storage', label: '数据存储' },
      ],
    },
    {
      type: 'category',
      label: 'IM 即时通讯',
      items: [
        { type: 'doc', key: 'message_architecture', id: 'im/message-architecture', label: '消息系统架构' },
        { type: 'doc', key: 'message_types', id: 'im/message-types', label: '消息类型详解' },
        { type: 'doc', key: 'message_send', id: 'im/message-send-receive', label: '消息收发流程' },
        { type: 'doc', key: 'session_management', id: 'im/session-management', label: '会话管理' },
        { type: 'doc', key: 'read_receipt', id: 'im/read-receipt', label: '已读回执' },
        { type: 'doc', key: 'offline_history', id: 'im/offline-history-message', label: '离线与历史消息' },
        { type: 'doc', key: 'socket_connection', id: 'im/socket-connection', label: 'Socket 连接' },
        { type: 'doc', key: 'contact_peer', id: 'im/contact-peer-management', label: '联系人管理' },
      ],
    },
    {
      type: 'category',
      label: '会议 SDK',
      items: [
        { type: 'doc', key: 'sdk_overview', id: 'sdk/sdk-overview', label: 'SDK 概述' },
        { type: 'doc', key: 'sdk_initialization', id: 'sdk/sdk-initialization', label: 'SDK 初始化' },
        { type: 'doc', key: 'meeting_operations', id: 'sdk/meeting-operations', label: '会议操作' },
        { type: 'doc', key: 'audio_video', id: 'sdk/audio-video-control', label: '音视频控制' },
        { type: 'doc', key: 'screen_share', id: 'sdk/screen-share-recording', label: '屏幕共享与录制' },
        { type: 'doc', key: 'e2ee_meeting', id: 'sdk/e2ee-meeting', label: 'E2EE 加密会议' },
      ],
    },
    {
      type: 'category',
      label: '数据库',
      items: [
        { type: 'doc', key: 'database_architecture', id: 'database/database-architecture', label: '数据库架构' },
        { type: 'doc', key: 'table_schema', id: 'database/table-schema', label: '表结构详解' },
        { type: 'doc', key: 'crud_operations', id: 'database/crud-operations', label: 'CRUD 操作' },
        { type: 'doc', key: 'fts_search', id: 'database/fts-search', label: '全文搜索' },
        { type: 'doc', key: 'migration_', id: 'database/migration', label: '版本迁移' },
      ],
    },
    {
      type: 'category',
      label: '日志系统',
      items: [
        { type: 'doc', key: 'logging_system', id: 'logging/logging-system', label: '日志系统架构' },
        { type: 'doc', key: 'log_categories', id: 'logging/log-categories', label: '日志分类参考' },
        { type: 'doc', key: 'log_encryption', id: 'logging/log-encryption', label: '日志加密' },
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      items: [
        { type: 'doc', key: 'api_overview', id: 'api/api-overview', label: 'API 总览' },
        { type: 'doc', key: 'api_infrastructure', id: 'api/api-infrastructure', label: '核心基础设施' },
        { type: 'doc', key: 'api_auth', id: 'api/api-auth', label: '认证与账户' },
        { type: 'doc', key: 'api_user', id: 'api/api-user-contact', label: '用户与联系人' },
        { type: 'doc', key: 'api_message', id: 'api/api-message', label: '消息系统' },
        { type: 'doc', key: 'api_session', id: 'api/api-session', label: '会话管理' },
        { type: 'doc', key: 'api_group', id: 'api/api-group', label: '群组与频道' },
        { type: 'doc', key: 'api_meeting', id: 'api/api-meeting', label: '会议系统' },
        { type: 'doc', key: 'api_file', id: 'api/api-file', label: '文件管理' },
        { type: 'doc', key: 'api_space', id: 'api/api-space', label: '空间与企业' },
        { type: 'doc', key: 'api_security', id: 'api/api-security', label: '安全与加密' },
        { type: 'doc', key: 'api_other', id: 'api/api-other', label: '其他功能' },
        { type: 'doc', key: 'ipc_api', id: 'api/ipc-api', label: 'IPC 接口' },
        { type: 'doc', key: 'store_api', id: 'api/store-api', label: 'Store 接口' },
        { type: 'doc', key: 'database_api', id: 'api/database-api', label: '数据库接口' },
        { type: 'doc', key: 'utils_api', id: 'api/utils-api', label: '工具函数' },
      ],
    },
    {
      type: 'category',
      label: 'IPC 通信',
      items: [
        { type: 'doc', key: 'ipc_architecture', id: 'ipc/ipc-architecture', label: 'IPC 通信架构' },
        { type: 'doc', key: 'ipc_send_receive', id: 'ipc/ipc-send-receive', label: 'IPC 发送与接收' },
        { type: 'doc', key: 'ipc_channels_ref', id: 'ipc/ipc-channels-reference', label: 'IPC 通道参考' },
        { type: 'doc', key: 'ipc_best_practices', id: 'ipc/ipc-best-practices', label: 'IPC 最佳实践' },
      ],
    },
    {
      type: 'category',
      label: '主进程模块',
      items: [
        { type: 'doc', key: 'mp_entry', id: 'main-process/entry-point', label: '主进程入口' },
        { type: 'doc', key: 'mp_window', id: 'main-process/window-management', label: '窗口管理' },
        { type: 'doc', key: 'mp_tray', id: 'main-process/tray-module', label: '系统托盘' },
        { type: 'doc', key: 'mp_notification', id: 'main-process/notification-module', label: '系统通知' },
        { type: 'doc', key: 'mp_updater', id: 'main-process/updater-module', label: '自动更新' },
      ],
    },
    {
      type: 'category',
      label: '渲染进程模块',
      items: [
        { type: 'doc', key: 'rp_main_app', id: 'renderer/main-app', label: '主应用渲染进程' },
        { type: 'doc', key: 'rp_vuex', id: 'renderer/vuex-modules', label: 'Vuex 状态管理' },
        { type: 'doc', key: 'rp_independent', id: 'renderer/independent-apps', label: '独立渲染应用' },
        { type: 'doc', key: 'rp_preload', id: 'renderer/preload-scripts', label: '预加载脚本' },
      ],
    },
    {
      type: 'category',
      label: '功能模块',
      items: [
        { type: 'doc', key: 'feat_screenshot', id: 'features/screenshot-module', label: '截屏模块' },
        { type: 'doc', key: 'feat_shortcut', id: 'features/shortcut-module', label: '快捷键模块' },
        { type: 'doc', key: 'feat_file', id: 'features/file-module', label: '文件处理模块' },
        { type: 'doc', key: 'feat_editor', id: 'features/editor-module', label: '编辑器模块' },
        { type: 'doc', key: 'feat_calendar', id: 'features/calendar-module', label: '日历模块' },
        { type: 'doc', key: 'feat_approval', id: 'features/approval-module', label: '审批模块' },
        { type: 'doc', key: 'feat_ai', id: 'features/ai-module', label: 'AI 模块' },
        { type: 'doc', key: 'feat_map', id: 'features/map-module', label: '地图模块' },
      ],
    },
    {
      type: 'category',
      label: '工具函数库',
      items: [
        { type: 'doc', key: 'util_data', id: 'utils/data-utils', label: '数据处理工具' },
        { type: 'doc', key: 'util_file', id: 'utils/file-utils', label: '文件处理工具' },
        { type: 'doc', key: 'util_crypto', id: 'utils/crypto-utils', label: '加密工具' },
        { type: 'doc', key: 'util_format', id: 'utils/format-utils', label: '格式化工具' },
        { type: 'doc', key: 'util_ui', id: 'utils/ui-utils', label: 'UI 工具' },
        { type: 'doc', key: 'util_function', id: 'utils/function-reference', label: '通用函数参考' },
      ],
    },
    {
      type: 'category',
      label: '组件库',
      items: [
        { type: 'doc', key: 'comp_overview', id: 'components/component-overview', label: '组件库概述' },
        { type: 'doc', key: 'comp_chat', id: 'components/chat-components', label: '聊天组件' },
        { type: 'doc', key: 'comp_layout', id: 'components/layout-components', label: '布局组件' },
        { type: 'doc', key: 'comp_dialog', id: 'components/dialog-components', label: '对话框组件' },
        { type: 'doc', key: 'comp_common', id: 'components/common-components', label: '通用组件' },
      ],
    },
    {
      type: 'category',
      label: '打包部署',
      items: [
        { type: 'doc', key: 'build_overview', id: 'build/build-overview', label: '构建系统概述' },
        { type: 'doc', key: 'build_nsis', id: 'build/nsis-config', label: 'NSIS 打包配置' },
        { type: 'doc', key: 'build_msi_appx', id: 'build/msi-appx-config', label: 'MSI/APPX 配置' },
        { type: 'doc', key: 'build_signing', id: 'build/code-signing', label: '代码签名' },
      ],
    },
    {
      type: 'category',
      label: '国际化',
      items: [
        { type: 'doc', key: 'i18n_system', id: 'i18n/i18n-system', label: '国际化系统' },
        { type: 'doc', key: 'i18n_lang_ref', id: 'i18n/language-reference', label: '语言包参考' },
      ],
    },
    {
      type: 'category',
      label: '重构优化',
      items: [
        { type: 'doc', key: 'index_', id: 'refactor/index', label: '重构任务总览' },
        { type: 'doc', key: 'p0_message', id: 'refactor/p0-message-manger', label: 'P0: 消息管理器拆分' },
        { type: 'doc', key: 'p0_database', id: 'refactor/p0-database-n1', label: 'P0: 数据库 N+1 修复' },
        { type: 'doc', key: 'p1_peer', id: 'refactor/p1-peer-api', label: 'P1: peerApi 优化' },
        { type: 'doc', key: 'p1_component', id: 'refactor/p1-component-split', label: 'P1: 大型组件拆分' },
        { type: 'doc', key: 'p1_memory', id: 'refactor/p1-memory-leak', label: 'P1: 内存泄漏修复' },
        { type: 'doc', key: 'p2_duplicate', id: 'refactor/p2-duplicate-code', label: 'P2: 重复代码消除' },
        { type: 'doc', key: 'p2_deep', id: 'refactor/p2-deep-clone', label: 'P2: 深拷贝优化' },
        { type: 'doc', key: 'p3_promise', id: 'refactor/p3-promise-modernize', label: 'P3: Promise 现代化' },
        { type: 'doc', key: 'p3_state', id: 'refactor/p3-state-management', label: 'P3: 状态管理优化' },
        { type: 'doc', key: 'Worker', id: 'refactor/p10-Worker', label: 'P10: 重构优化' },
      ],
    },
  ],
};

export default sidebars;
